### ISSUE TITLE
Feature: Write new repo's description

### ISSUE THREAD

**Issue by StraykerPL** [StraykerPL/Binder#1]
**Is your feature request related to a problem? Please describe.**
Current repo's description on GitHub is not sufficient.

**Describe the solution you'd like**
More substantial description will help to recognise project on platform.

**Describe alternatives you've considered**

**Additional context**

**Comment by Sokonikun** [comment]
Binder is simple software allowing you to create ToDo and custom lists of tasks in clean and readable way. You can create task from default pattern: name, description, beginning date and deadline, or define your own one.

**Comment by StraykerPL** [comment]
This ticket doesn't require PR. Manual review request @StraykerPL

**Comment by StraykerPL** [comment]
Approved

**Comment by StraykerPL** [comment]
This PR doesn't require testing. Moving to Done.
